### ISSUE TITLE
derive public key hash in c#

### ISSUE THREAD

**Issue by AdamMachera** [CardanoSharp/cardanosharp-wallet#105]
How public key hash can be derived in c# similary to this article
https://cardano.stackexchange.com/questions/8021/derive-public-key-hash-from-bech32-address-using-python

using cardanosharp-wallet?

**Comment by nothingalike** [comment]
```cs
using CardanoSharp.Wallet.Models.Addresses;
using CardanoSharp.Wallet.Extensions;

var address = new Address("addr_test1qpu5vlrf4xkxv2qpwngf6cjhtw542ayty80v8dyr49rf5ewvxwdrt70qlcpeeagscasafhffqsxy36t90ldv06wqrk2qum8x5w");
var addressBytes = address.GetBytes();

Console.WriteLine($"Address Hash: {addressBytes.ToStringHex()}");

var addressBytesWithoutHeader = new byte[addressBytes.Length - 1];
Buffer.BlockCopy(addressBytes, 1, addressBytesWithoutHeader, 0, addressBytesWithoutHeader.Length);

Console.WriteLine($"Address Hash w/o Network: {addressBytesWithoutHeader.ToStringHex()}");

//this is what you are looking for
var paymentHash = new byte[addressBytesWithoutHeader.Length / 2];
Buffer.BlockCopy(addressBytesWithoutHeader, 0, paymentHash, 0, paymentHash.Length);

Console.WriteLine($"PublicKeyHash: {paymentHash.ToStringHex()}");
```

this should do it

**Comment by nothingalike** [comment]
we could/should turn these into helper functions

thoughts?
@safestak-keith @NicholasMaselli @Daniel-SchaeferJ

**Comment by NicholasMaselli** [comment]
Oh yeah definitely I think very commonly used Cardano functionality should have as simple as possible functions / implementation. Just a matter of time allocation / resources / funding

**Comment by Daniel-SchaeferJ** [comment]
Yeah I'm in agreement here. With the very fluent interface design of the library, turning these into helper functions would more coincide with the ease of use that the library provides and its architecture in general.

**Comment by AdamMachera** [comment]
Thanks, solution that you provided works
