### ISSUE TITLE
How to generate skey compatible with cardano-cli

### ISSUE THREAD

**Issue by AdamMachera** [CardanoSharp/cardanosharp-wallet#109]
Wanted to ask if it is possible to generate skey that would be compatible with cardano-cli
In cli we can create skey using this command
cardano-cli address key-gen \
    --verification-key-file payment.vkey \
    --signing-key-file payment.skey

Currently I have scenario that I have nami account for which I have 24 words.
I was wondering how I can create skey for it

IMnemonicService mnemonicService= new MnemonicService();
Mnemonic mnemonic = mnemonicService.Restore("24_words");
PrivateKey rootKey = mnemonic.GetRootKey();
System.IO.File.WriteAllBytes(@"c:\temp\some.skey", rootKey.Key);

However the content of this file isn't similar to what is generated with cardano-cli.
We have most of the system written with cardano-cli wrapper so we are not yet ready to fully migrate to cardanosharp-wallet
hence I would like to use MnemonicService and generate signing key and use it in the cardano-cli command.

**Comment by nothingalike** [comment]
btw `cscli` is like `cardano-cli` but headless and uses koios. its still WIP but it can handle a lot of the mnemonic, key, and address functionality. feel free to add an issue for requested features if you like

**Comment by AdamMachera** [comment]
Thanks, link to it was very helpful.
