### ISSUE TITLE
blazor wasm dotnet 7  (not a issue, but a remark)

### ISSUE THREAD

**Issue by cmorgado** [CardanoSharp/cardanosharp-wallet#114]
I've just tested blazor wasm with dotnet7 

```
 public partial class Index: ComponentBase
    {
        private IAddressService addressService = new AddressService();
        private IMnemonicService service = new MnemonicService();

        public int privateKeyStr { get; set; }
        protected override void OnInitialized()
        {
            string q = "";
            string words = "art forum devote street sure rather head chuckle guard poverty release quote oak craft enemy";
            var mnemonic = new MnemonicService().Restore(words);

            // Fluent derivation API
            var derivation = mnemonic
                .GetMasterNode("password")      // IMasterNodeDerivation
                .Derive(PurposeType.Shelley)    // IPurposeNodeDerivation
                .Derive(CoinType.Ada)           // ICoinNodeDerivation
                .Derive(0)                      // IAccountNodeDerivation
                .Derive(RoleType.ExternalChain) // IRoleNodeDerivation
                                                //or .Derive(RoleType.Staking) 
                .Derive(0);                     // IIndexNodeDerivation

            PrivateKey privateKey = derivation.PrivateKey;
            PublicKey publicKey = derivation.PublicKey;

           

            base.OnInitialized();
        }
    }
```

And it works!
looks promising!

**Comment by nothingalike** [comment]
this is amazing!
@Mercurial i believe you wanted this support, right?

**Comment by Mercurial** [comment]
> this is amazing!
> 
> @Mercurial i believe you wanted this support, right?

Yep I've been testing this secretly since dotnet 7 was released :D, time to create a blazor / C# wallet

**Comment by eddex** [comment]
> Yep I've been testing this secretly since dotnet 7 was released :D, time to create a blazor / C# wallet

Eternl is using Blazor too, but they are not open sourcing their code. Would be cool to have a .NET powered open source wallet 👌

**Comment by Mercurial** [comment]
> > Yep I've been testing this secretly since dotnet 7 was released :D, time to create a blazor / C# wallet
> 
> Eternl is using Blazor too, but they are not open sourcing their code. Would be cool to have a .NET powered open source wallet 👌

wait what? really????

**Comment by cmorgado** [comment]
I was into the impression that eternl was using VUE...


   -




Clark Alesna ***@***.***> escreveu no dia terça, 22/11/2022
à(s) 09:04:

**Comment by eddex** [comment]
> wait what? really? That's awesome!!!
> 
> I hope they open source it!

They won't. I've asked them multiple times. They want to protect their IP and innovations from being stolen by other projects.



> I was into the impression that eternl was using VUE...

I can't find any evidence from their frontend. Maybe they switched, I was pretty sure I've seen that they are using Blazor at some point.

**Comment by cmorgado** [comment]
done
