### ISSUE TITLE
WordList lookup for pre-loading allWords 

### ISSUE THREAD

**Issue by safestak-keith** [CardanoSharp/cardanosharp-wallet#12]
Currently file IO to load all available words for a word list happens every time the KeyService BIP39 methods are called (Generate/Restore). 

Since they are immutable arrays can we pre-load these upon initialisation of the KeyService instance? Perhaps even initialised instance variables aren't required and a static readonly IDictionary<WordLists, string[]> master-lookup using an approach like https://github.com/realindiahotel/BIP39.NET/tree/master/BIP39.NET/BIP39.NET/Wordlists could work?

**Comment by nothingalike** [comment]
@safestak-keith is this done? i see a PR associated with this issue has been merged

**Comment by safestak-keith** [comment]
This one is still active but I can start looking into it once we agree on the implementation. There are a few options:
 - Pre-loading these Dictionary lookups upon KeyService initialisation file IO costs in the beginning 
 - Declaring the word lookups in code such as in https://github.com/realindiahotel/BIP39.NET/tree/master/BIP39.NET/BIP39.NET/Wordlists

**Comment by nothingalike** [comment]
@safestak-keith 
I think the second option seems the best imo

**Comment by safestak-keith** [comment]
Agree with you there. Will start dev work soon!
