### ISSUE TITLE
Address service is removed in v5.0.1

### ISSUE THREAD

**Issue by hparsafar** [CardanoSharp/cardanosharp-wallet#143]
Address service is removed in v5.0.1, how can we have the same functionality in this version?

**Comment by Sarmaad** [comment]
Have a look at AddressUtility; it has most of what you might need.

**Comment by nothingalike** [comment]
The website has some information as well

https://cardanosharp.com/docs/addresses

**Comment by nothingalike** [comment]
ill put some time in updating the docs

**Comment by hparsafar** [comment]
thanks:) please answer my other issue too. 
https://github.com/CardanoSharp/cardanosharp-wallet/issues/144
