### ISSUE TITLE
`Bech32.Decode` tests fail on valid BIP173 testvectors

### ISSUE THREAD

**Issue by tweakch** [CardanoSharp/cardanosharp-wallet#16]
https://github.com/CardanoSharp/cardanosharp-wallet/blob/71b99231b324da622b1e074589f90c264993727d/CardanoSharp.Wallet.Test/Bech32Tests.cs#L26-L61

BIP173 defines valid test vectors for Bech32 [here](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#test-vectors). 

All parameters for `InlineDataAttribute` need review and must be fixed first. (ie. `expectedWitVer` and `expectedHrp`)

**Comment by tweakch** [comment]
While passing all the BIP173 testvectors would be nice, we could just focus on [CIP19](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0019/CIP-0019.md) for starters and reopen this issue if necessary

**Comment by tweakch** [comment]
oh... 70f7be6350a3281987d63a58d105e9c9b959836a 👍

**Comment by nothingalike** [comment]
> oh... [70f7be6](https://github.com/CardanoSharp/cardanosharp-wallet/commit/70f7be6350a3281987d63a58d105e9c9b959836a) 👍

I implemented the CIP19 test vectors, right? or did i miss something?

**Comment by tweakch** [comment]
LGTM
