### ISSUE TITLE
Improve `TransactionBuilder`

### ISSUE THREAD

**Issue by tweakch** [CardanoSharp/cardanosharp-wallet#21]
## Why we should improve `TransactionBuilder`

Reading through the **Transactions Section** in the README I noticed that `TransactionBuilder` doesn't really help `build` the transaction. 

So I extracted the interface for `TransactionBuilder` and noticed that it looks more like a `TransactionSerializer`

```csharp
public interface ITransactionBuilder
{
    long CalculateFee(byte[] transaction);
    byte[] SerializeBody(TransactionBody transactionBody);
    byte[] SerializeTransaction(Transaction transaction);
}
```
***We should name it accordingly.*** And since `Serializers` don't `CalculateFees` but `TransactionBuilders` ***could*** lets assume we do this for now...

```csharp
public interface ITransactionSerializer
{
    byte[] SerializeBody(TransactionBody transactionBody);
    byte[] SerializeTransaction(Transaction transaction);
}

public interface ITransactionBuilder
{
    Transaction Transaction { get; }
    int Fees { get; }
    // more to come...
}
```

Since we have a `TransactionSerializer` this should also be able to `DeserializeBody` and `DeserializeTransaction`

```csharp
public interface ITransactionSerializer
{
    byte[] SerializeBody(TransactionBody transactionBody);
    byte[] SerializeTransaction(Transaction transaction);
    TransactionBody DeserializeBody(byte[] transactionBody);
    Transaction DeserializeTransaction(byte[] transaction);
}
```

*But of course* we need a `TransactionBuilder` that helps create `Transaction` we can serialize/deserialize by `ITransactionSerializer`. 

## How we could improve `TransactionBuilder`

So what are transactions? They modify the ledger and can: 
* contain Certificates
* contain Metadata
* contain Scripts (Native / SmartContracts)
* be signed (by 1 to n witnesses)
* spend UTxOs (inputs = outputs - fees) 
* ...and more (like minting / burning tokens, but let's leave this usecase aside for now)
 
So I propose the `ITransactionBuilder` to look like this:
```cs
public interface ITransactionBuilder
{
    Transaction Transaction { get; }
    int Fees { get; }

    ITransactionBuilder AddCertificate(Certificate certificate);
    ITransactionBuilder AddMetadata(Metadata metadata); // base type for PoolMetadata
    ITransactionBuilder AddInput(Address addr, int index);
    ITransactionBuilder AddOutput(Address addr, int amount);
    ITransactionBuilder AddScript(NativeScript script);

    Transaction Sign(params PrivateKey[] witnesses);
}
```

Notice: 

* It looks like a `StringBuilder`... 
* `AddXXX(...)` are like `StringBuilder.Append` 
* `Sign(...)` is the equivalent to `StringBuilder.ToString`
* We don't need a `Build()` method, since `Transaction` is updated and maintained by the `TransactionBuilder` "as-we-build"...
* Sign() would return a `new Transaction` so that we don't "loose" our building progress if the transaction fails. 
* We have full control over the transaction being built via the `Transaction` property

What are your thoughts / inputs? Should we pursue this?

**Comment by nothingalike** [comment]
100% agree! This was the next thing I was going to tackle. Destroying the TransactionBuilder.

I definitely like your analysis of the current state and where we can take it. I'm fully on board for this action. I was planning on implementing a Builder Pattern which is essentially your `AddXXX()` approach. The other thing I was going to do is turn the Serialize methods in to Extension methods since there are times where you might need to re-serialize certain sections of the transaction while not other parts. If you take a look at the current NativeScriptExtensions...

```cs
namespace CardanoSharp.Wallet.Extensions.Models
{
    public static class NativeScriptExtension
    {
        public static byte[] GetPolicyId(this NativeScript nativeScript)
        {
            BigEndianBuffer buffer = new BigEndianBuffer();
            buffer.Write(new byte[] { 0x00 });
            buffer.Write(nativeScript.GetCBOR().EncodeToBytes());
            return HashUtility.Blake2b244(buffer.ToArray());
        }

        public static CBORObject GetCBOR(this NativeScript nativeScript)
        {
            var nativeScriptCbor = CBORObject.NewArray();

            if(nativeScript.ScriptPubKey != null)
                nativeScriptCbor.Add(nativeScript.ScriptPubKey.GetCBOR());

            if (nativeScript.ScriptAll != null)
                nativeScriptCbor.Add(nativeScript.ScriptAll.GetCBOR());

            if (nativeScript.ScriptAny != null)
                nativeScriptCbor.Add(nativeScript.ScriptAny.GetCBOR());

            if (nativeScript.ScriptNofK != null)
                nativeScriptCbor.Add(nativeScript.ScriptNofK.GetCBOR());

            if (nativeScript.InvalidAfter != null)
                nativeScriptCbor.Add(nativeScript.InvalidAfter.GetCBOR());

            if (nativeScript.InvalidBefore != null)
                nativeScriptCbor.Add(nativeScript.InvalidBefore.GetCBOR());

            return nativeScriptCbor;
        }
    }
}
```

You can see how I separated the CBOR construction from the Serialization. This could even be approved upon but I was just testing my thoughts here. This is essentially how I saw the new approach for Serialization.
