### ISSUE TITLE
AddressService.GetAddressBytes does not exists

### ISSUE THREAD

**Issue by shawnsblog** [CardanoSharp/cardanosharp-wallet#25]
As per the example shown on how to create a transaction, addressService.GetAddressBytes is used during TransactionOutput, however is not available via Nuget package, nor via browsing the repository.

**Comment by nothingalike** [comment]
Ah sorry about that. We're moving fast these days making updates to the library. We definitely missed that README update.

Heres what you want to do...
```cs
var addressBytes = CardanoSharp.Wallet.Encoding.Bech32.Decode(addressStr, out _, out _);
```

You can also use the new `Address` model.
```cs 
var addressModel = new Address(addressStr);
var addressBytes = addressModel.GetBytes();
```

**Comment by shawnsblog** [comment]
Thanks for the update,

**Comment by nothingalike** [comment]
Readme has been updated.
