### ISSUE TITLE
Address validity

### ISSUE THREAD

**Issue by avolkov-dev** [CardanoSharp/cardanosharp-wallet#27]
Is there are any way to check address validity?
Something like
```

public static bool IsValid(string address){
....
}
```

**Comment by tweakch** [comment]
`Bech32.IsValid()` will give you `true` or `false` but it uses `Bech32.Bech32Decode(...)` which is not perfect yet (see #16)

@nothingalike Might be a good ExtensionMethod for string and/or Address...

**Comment by avolkov-dev** [comment]
yes, looks like
```
            var isValid =
                Bech32.IsValid(
                    "addr1qyjwch0yyszpgs9l68dn9yjmh2gee8xqvn7mthtrc7fl5p9gfjjjak6t0cutp4mg0wagzdmsn8wlvqq428u44dqyysgsxtw3jk");
            Assert.True(isValid);
```

Is failing on valid address

https://explorer.cardano.org/en/address?address=addr1qyjwch0yyszpgs9l68dn9yjmh2gee8xqvn7mthtrc7fl5p9gfjjjak6t0cutp4mg0wagzdmsn8wlvqq428u44dqyysgsxtw3jk

**Comment by nothingalike** [comment]
sounds good. Ill prioritize bech32 issues.

**Comment by tweakch** [comment]
> Is failing on valid addresses

@nothingalike  I bet this is the length.. cardano allows addresses longer than specified in BIP32... could be wrong

**Comment by nothingalike** [comment]
@avolkov-dev main has been updated, nuget package 0.2.2
thank you for your issue!

**Comment by avolkov-dev** [comment]
Thanks a lot :-)
