### ISSUE TITLE
Using paymentPub and paymentPrv key values as VKey and SKey values throws System.ArgumentException in Chaos.NaCl.Ed26519.Sign during witness creation

### ISSUE THREAD

**Issue by shawnsblog** [CardanoSharp/cardanosharp-wallet#29]
Following the readme assigned to this project, the witness creation process states the following...

`new VKeyWitness()
        {
            VKey = paymentPub.Key,
            SKey = paymentPrv.Key
        }`

However, reviewing the documentation on the following page...
[developers.cardano.org](https://developers.cardano.org/docs/get-started/cardanosharp-wallet/)
shows the following...

`new VKeyWitness()
        {
            VKey = paymentPub,
            SKey = paymentPrv
        }`

The original Github readme gives the impression that you should be able to pass the publicKey.key and privateKey.key values for VKey and SKey, however, the developer.cardano.org link gives the impression that you need to pass the chaincode as well and generate the Tuple assigning them to the VKey and SKey values.

Can you clarify?

**Comment by nothingalike** [comment]
Is this still an issue? I believe the latest README updates have resolved the confusion. Please let me know if theres more that can be clarified

**Comment by shawnsblog** [comment]
This is resolved. Thank you.
