### ISSUE TITLE
daedalus address to bytes

### ISSUE THREAD

**Issue by avolkov-dev** [CardanoSharp/cardanosharp-wallet#35]
Hello. Could you point me on how to generate bytes from daedalus address?
`DdzFFzCqrht9W56zJGEFvHHywdeXZiGVYGqVhoZj6SRrS9o2HNLmorEzZhKm7khqfBKvCaTKGLtTnQSToxuvdzJTkQqcAf6f2ErxbSKS` -> byte[]

**Comment by tweakch** [comment]
Has this been hashed? Can you give some context about the encoding? I can't quite figure out how you ended up with this `base64-looking` string.

**Comment by nothingalike** [comment]
Is this a Byron Address?

**Comment by avolkov-dev** [comment]
> 
> 
> Has this been hashed? Can you give some context about the encoding? I can't quite figure out how you ended up with this `base64-looking` string.
> 
> the naive approach would be to simply convert it to bytes:
> 
> ```cs
> var bytes = Convert.FromBase64String("Ddz..."); 
> Console.WriteLine(bytes.ToStringHex());
> ```

yeah, this worked for me.
