### ISSUE TITLE
Stake/Reward Address returning the payment address instead 

### ISSUE THREAD

**Issue by safestak-keith** [CardanoSharp/cardanosharp-wallet#43]
AddressService GetAddress is returning the payment address instead of the stake/reward address. This is due to the same code being executed for both Enterprise and Reward addresses using the payment public key [AddressService:38](https://github.com/CardanoSharp/cardanosharp-wallet/blob/fcee7894d105c650e6becee40380dd4fc0d88988/CardanoSharp.Wallet/AddressService.cs#L39) 

```c#
            byte[] addressArray;
            switch (addressType)
            {
                case AddressType.Base:
                    addressArray = new byte[1 + paymentEncoded.Length + stakeEncoded.Length];
                    addressArray[0] = header;
                    Buffer.BlockCopy(paymentEncoded, 0, addressArray, 1, paymentEncoded.Length);
                    Buffer.BlockCopy(stakeEncoded, 0, addressArray, paymentEncoded.Length + 1, stakeEncoded.Length);
                    break;
                case AddressType.Enterprise:
                case AddressType.Reward:
                    addressArray = new byte[1 + paymentEncoded.Length];
                    addressArray[0] = header;
                    Buffer.BlockCopy(paymentEncoded, 0, addressArray, 1, paymentEncoded.Length);
                    break;
                default:
                    throw new Exception("Unknown address type");
            }
```

It should also still be valid with a null payment public key parameter which will currently throw an exception. Following from that, generating an enterprise address should also work with a null stake public key parameter. An easy fix can be applied with some null friendly args but perhaps a discussion is warranted - should we have SDK methods per address type? e.g. `GetBaseAddress(PublicKey payment, PublicKey stake, NetworkType networkType); GetEnterpriseAddress(PublicKey payment, NetworkType networkType); GetRewardAddress(PublicKey stake, NetworkType networkType);` this should save our SDK consumers from any unexpected behaviour and make things explicit.

**Comment by MikeEndes** [comment]
To get the correct stake key you can correct with the following code correction, but the Enterprise Address still needs implemented it looks like.  I have tested a local copy the stake address correction below and it works as expected.
                case AddressType.Enterprise:
                case AddressType.Reward:
                    //addressArray = new byte[1 + paymentEncoded.Length];
                    //addressArray[0] = header;
                    //Buffer.BlockCopy(paymentEncoded, 0, addressArray, 1, paymentEncoded.Length);
                    //break;
                    addressArray = new byte[1 + stakeEncoded.Length];
                    addressArray[0] = header;
                    Buffer.BlockCopy(stakeEncoded, 0, addressArray, 1, stakeEncoded.Length);
                    break;

**Comment by nothingalike** [comment]
ok so it looks like the Enterprise and Reward addresses are the same approach just one takes the Payment Public key and the other takes the Stake Public Key

**Comment by MikeEndes** [comment]
> ok so it looks like the Enterprise and Reward addresses are the same approach just one takes the Payment Public key and the other takes the Stake Public Key

I think so.  I just know that the Enterprise Address does not have staking capabilities.  I have to worked with them yet.

**Comment by safestak-keith** [comment]
Yeah with that in mind we should be either 
 - Be lenient with accepting nulls for the payment public key when generating stake/reward addresses or nulls for the stake public key when generating enterprise addresses
 - Expose separate methods per address type with exact parameters
