### ISSUE TITLE
Question about deriving addresses and encrypting private keys

### ISSUE THREAD

**Issue by danbigthink** [CardanoSharp/cardanosharp-wallet#46]
Hi,

I love this project, thank you!

I'm trying to mimic how Daedalus does a few things. Currently Daedalus shows used and unused addresses in the Receive tab.
I am capable of deriving 20 addresses at a time and checking with a server to determine if these addresses are used or not. I end up with a list of x used addresses and the next 20 available unused addresses.

I have this all working and it's exactly the same as the Daedalus receive screen. The only issue I'm facing is how to achieve this without access to the private keys as they're encrypted with the spending password.

I have a couple of implementation examples of this but sadly if they're IAccountNodeDerivation or simply byte[] Key, byte[] Chaincode for both private key and public key that means I need the private key to derive the next 20 addresses.

Thanks for your help,
Dan

**Comment by nothingalike** [comment]
Hey @danbigthink 

Glad to hear you are finding your way around the library!

So the `PublicKey` class has extensions similarly to `AccountNodeDerivation` where you can `Derive()`

Try this
```cs
            var paymentPublic = new PublicKey(account.PublicKey.Key, account.PublicKey.Chaincode)
                .Derive(RoleType.ExternalChain)
                .Derive(0)
                .PublicKey;
```

**Comment by nothingalike** [comment]
this as well

```cs
var paymentPublic = account.PublicKey
   .Derive(RoleType.ExternalChain)
   .Derive(0)
   .PublicKey;
``

**Comment by danbigthink** [comment]
Hey @nothingalike,

Thanks so much. I was traversing the paths manually in a loop incrementing each path index and found that was really holding me up and just couldn't figure out how to do that without the private key.
Using this method I can still traverse using an index and I don't need the private key.

Have a good one!
Dan

**Comment by nothingalike** [comment]
@danbigthink Awesome! Glad to hear.
