### ISSUE TITLE
CIP 2 - Coin Selection Algorithms for Cardano

### ISSUE THREAD

**Issue by nothingalike** [CardanoSharp/cardanosharp-wallet#53]
## As described in the CIP Doc

Algorithms
This section describes the coin selection algorithms used by Cardano Wallet, along with step-by-step descriptions of the computations involved.

All algorithms implement a common interface, as described in the [Interface](https://cips.cardano.org/cips/cip2/#interface) section.

There are two main algorithms used by Cardano Wallet:

[Largest-First](https://cips.cardano.org/cips/cip2/#largest-first)
[Random-Improve](https://cips.cardano.org/cips/cip2/#random-improve)
In general, Cardano Wallet gives priority to the [Random-Improve](https://cips.cardano.org/cips/cip2/#random-improve) algorithm, as experimental evidence shows that it performs better at [minimising dust](https://cips.cardano.org/cips/cip2/#goals) and maintaining a UTxO set with [useful outputs](https://cips.cardano.org/cips/cip2/#goals). (See [Self Organisation in Coin Selection](https://cips.cardano.org/cips/cip2/#self-organisation-in-coin-selection) for more details.)

However, in rare cases, the [Random-Improve](https://cips.cardano.org/cips/cip2/#random-improve) algorithm may fail to produce a result. In such cases, Cardano Wallet will fall back to the [Largest-First](https://cips.cardano.org/cips/cip2/#largest-first) algorithm.

--------------------------------------

### CIP Link: https://cips.cardano.org/cips/cip2/#algorithms

# Bounty: 250 ADA

**Comment by safestak-keith** [comment]
For reference there are two open-source implementations that you could try to port over in C#:
 - [cardano-serialization-lib)](https://github.com/Emurgo/cardano-serialization-lib/blob/master/rust/src/tx_builder.rs#L199) has both RandomImprove and LargestFirst approaches with multi-asset optimised ones
 - [Nami (JavaScript) ](https://github.com/Berry-Pool/nami-wallet/blob/6c92c1e171af04cabec64bb095b0cf8163b72be2/src/lib/coinSelection.js) has RandomImprove only
