### ISSUE TITLE
CIP 8 - Message Signing

### ISSUE THREAD

**Issue by nothingalike** [CardanoSharp/cardanosharp-wallet#54]
### CIP Link: https://cips.cardano.org/cips/cip8/

# Bounty: 250 ADA

**Comment by cmorgado** [comment]
this means that whoever implements this on cardano-sharp and "wins" the bounty receives 250Ada?

**Comment by nothingalike** [comment]
@cmorgado that is correct. once the PR with the feature has been approved, ill ask for your cardano address. Then I'll send the bounty from the CardanoSharp Treasury which is funded via the SHARP Stake Pool

Treasury Account: https://cardanoscan.io/stakeKey/3ed7e5cd8fb1388a639e934ebb996c096ef244543f2b9a11f2589b6f
