### ISSUE TITLE
Token metadata JSON asset name field cannot be defined using anonymous type object.

### ISSUE THREAD

**Issue by CodeBlitz** [CardanoSharp/cardanosharp-wallet#60]
Tokens and NFTs require metadata with some field names that represent unique values. PolicyID and AssetName must appear in the metadata as the actual field names in the JSON structure.

`{
  "721": {
    "f46ba28b19f7f35df3a5dbb9efeddee4bdd61ea33ba7fee2c31c655a": {
      "Token012382": {
        "name": "Fun tokens, just for fun.",
        "image": "ipfs://ipfs/QmVE1Ssn2wzc9Rg1emQCtxkMuWdG2AW21VpgbrDftmqnz7"       
      }
    }
  }
}`

AuxiliaryDataBuilder is provided to assign metadata. The AddMetadata method accepts an object type which is then used to generate the JSON structure. All examples show using an anonymous type.

C# code using variables for field names.
`metadataBuilder.AddMetadata(721, new
            {
                policyIdVariable = new
                {
                    assetNameVariable = new
                    {
                        name = "Fun tokens, just for fun.",                       
                        image = "ipfs://ipfs/QmVE1Ssn2wzc9Rg1emQCtxkMuWdG2AW21VpgbrDftmqnz7"                        
                    }
                }
            });`

The code above fails to use the variable's (policyIdVariable, assetNameVariable) values as field names. This is because anonymous types are defined at compile-time. As a test, to confirm the challenge, I hardcoded the PolicyID and AssetName as illustrated below.

C# hardcoded
`metadataBuilder.AddMetadata(721, new
            {
                f46ba28b19f7f35df3a5dbb9efeddee4bdd61ea33ba7fee2c31c655a = new
                {
                    Token012382 = new
                    {
                        name = "Fun tokens, just for fun.",                       
                        image = "ipfs://ipfs/QmVE1Ssn2wzc9Rg1emQCtxkMuWdG2AW21VpgbrDftmqnz7"                        
                    }
                }
            });`

This did generate the desired metadata for a token minting transaction. There may be an easy way to dynamically define a field name on an anonymous type, but I am unaware of it. Is it possible to pass a JSON formatted string to the AddMetadata method instead of using a class structure? 

Any advice or help is appreciated.

**Comment by CodeBlitz** [comment]
Problem solved using dynamics.

**Comment by nothingalike** [comment]
> Problem solved using dynamics.

@CodeBlitz Could you share a code example of your solution?
