### ISSUE TITLE
How can I convert byte[] privetkey to privet key ?

### ISSUE THREAD

**Issue by ramincsy2** [CardanoSharp/cardanosharp-wallet#71]
How can I convert byte[] privetkey to privet key ?

**Comment by nothingalike** [comment]
I'm not 100% sure I understand but heres one way

```cs
byte[] keyInBytes; //this is your byte[] privetkey
var privateKey = new PrivateKey()
{
    Key = keyInBytes
}
```

**Comment by ramincsy2** [comment]
@nothingalike
it did not work

**Comment by nothingalike** [comment]
@ramincsy2 can you provide more information on what you are trying to do?

**Comment by ramincsy2** [comment]
@nothingalike 
I want to make a wallet and keep private and public keys
But keys are an array of bytes

**Comment by safestak-keith** [comment]
> I want to make a wallet and keep private and public keys But keys are an array of bytes

Are you on the[ CardanoSharp discord](https://discord.gg/fT777VUA)? Please [ask the question there](https://discord.gg/fT777VUA) for quicker/easier troubleshooting as opposed to creating a GitHub issue. 

The most important question from my end is - how did you get those byte arrays in the first place? Is your key an extended private/signing key? Then try `new PrivateKey(keyInBytes[..64], keyInBytes[64..])` If it is not extended you can try `new PrivateKey(keyInBytes, Array.Empty<Byte>())`. Either way please continue the discussion in Discord.

**Comment by safestak-keith** [comment]
@ramincsy2 I will close this issue since we've been talking on Discord and it seems like you've got a better understanding
